### ISSUE TITLE
broken loading ?

### ISSUE THREAD

**Issue by rom1504** [dazed-sheep/dazed-sheep#8]
I'm getting this on the auto-updating server:
```
TypeError: Cannot read property 'blocks' of undefined
    at Object.module.exports.server (/home/dazed-sheep/auto-sheep/dazed-sheep/lib/plugins/world.js:14:90)
    at /home/dazed-sheep/auto-sheep/dazed-sheep/index.js:26:50
    at Array.forEach (native)
    at MCServer.connect (/home/dazed-sheep/auto-sheep/dazed-sheep/index.js:26:8)
    at Object.createMCServer (/home/dazed-sheep/auto-sheep/dazed-sheep/index.js:11:12)
    at Object.<anonymous> (/home/dazed-sheep/auto-sheep/dazed-sheep/app.js:12:27)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by rom1504** [comment]
getting the same in local.

@mhsjlw fix it ;)

**Comment by mhsjlw** [comment]
Is this when you start the server? Did you try to place a block then got this error?

**Comment by rom1504** [comment]
I get this when starting the server, it immediately crashes.

**Comment by mhsjlw** [comment]
Ok, I'll investigate it further.

**Comment by mhsjlw** [comment]
Is this error when you join the server or just when you start it? I've started the server on the newest commit, and it didn't crash.

**Comment by rom1504** [comment]
ok I tried rm -rf node_module and npm install and that fixed it.
Weird.

Anyway, "fixed"
